tasks:
  - before: npm install -g firebase-tools
  - init: npm install && npm run build
    command: npm run start
    command: npm serve

image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - elmTooling.elm-ls-vscode@0.8.0:rb3k4mPelyC4Fqod9UBvvA==